remote_theme: pmarsceill/just-the-docs
title: Test Navigation
description: Testing theme navigation menus
repository: "pdmosses/test-nav"
# Aux links for the upper right navigation
aux_links:
  "test-nav on GitHub":
    - "//github.com/pdmosses/test-nav"
plugins:
    - jekyll-seo-tag
compress_html:
  blanklines: true
mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'
